language: node_js

install:
  - rvm install 2.2.0
  - gem install bundler
  - bundle
  - bundle exec ruby src/download_old.rb

script:
  - servers/metaphysics/setup.sh
  - bundle exec ruby src/compare.rb

  - bundle exec ruby src/upload_new.rb
